---
- name: Check available updates
  shell: |
    dnf check-update \
    --disablerepo="*" \
    --enablerepo="{{ rhel_repo_pattern }}" || true
  register: patch_check

- name: Show available updates
  debug:
    var: patch_check.stdout_lines

- name: Check current uptime
  shell: uptime
  register: current_uptime

- name: Display current uptime
  debug:
    var: current_uptime.stdout

- name: Check disk utilization
  shell: df -h
  register: disk_usage

- name: Display disk usage
  debug:
    var: disk_usage.stdout_lines
